"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let a = 'hello';
console.log(a);
let b = 'owu';
console.log(b);
let c = 'com';
console.log(c);
let d = 'ua';
console.log(d);
let e = 1;
console.log(e);
let f = 10;
console.log(f);
let g = -999;
console.log(g);
let h = 123;
console.log(h);
const PI = 3.14;
console.log(PI);
let i = 2.7;
console.log(i);
let j = 16;
console.log(j);
let k = true;
console.log(k);
let l = false;
console.log(l);
//# sourceMappingURL=HW_1.1.js.map